# Generated by Django 5.2.13 on 2026-04-19 01:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('minor_unit', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('dialing_code', models.CharField(blank=True, max_length=8)),
                ('is_sender_enabled', models.BooleanField(default=False)),
                ('is_destination_enabled', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='countries.currency')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CountryCorridor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_send_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_send_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_corridors', to='countries.country')),
                ('source_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_corridors', to='countries.country')),
                ('destination_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_corridors', to='countries.currency')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_corridors', to='countries.currency')),
            ],
            options={
                'ordering': ('source_country__name', 'destination_country__name'),
                'constraints': [models.UniqueConstraint(fields=('source_country', 'destination_country'), name='unique_country_corridor')],
            },
        ),
    ]
