# Generated by Django 5.2.13 on 2026-04-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_sender_enabled', 'is_destination_enabled'], name='countries_c_is_send_afb0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='countrycorridor',
            index=models.Index(fields=['source_country', 'destination_country', 'is_active'], name='countries_c_source__e3b35d_idx'),
        ),
        migrations.AddConstraint(
            model_name='countrycorridor',
            constraint=models.CheckConstraint(condition=models.Q(('min_send_amount__gte', 0)), name='corridor_min_send_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='countrycorridor',
            constraint=models.CheckConstraint(condition=models.Q(('max_send_amount__gte', models.F('min_send_amount'))), name='corridor_max_send_amount_gte_min'),
        ),
    ]
