# Generated by Django 5.2.13 on 2026-04-21 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_default_payout_routes(apps, schema_editor):
    fee_rule_model = apps.get_model("quotes", "FeeRule")
    payout_provider_model = apps.get_model("countries", "PayoutProvider")
    corridor_payout_method_model = apps.get_model("countries", "CorridorPayoutMethod")
    corridor_payout_provider_model = apps.get_model("countries", "CorridorPayoutProvider")

    provider_defaults = {
        "mobile_money": {
            "code": "internal_mobile_money",
            "name": "Internal mobile money operations",
            "display_order": 10,
        },
        "bank_deposit": {
            "code": "internal_bank_deposit",
            "name": "Internal bank deposit operations",
            "display_order": 20,
        },
    }

    providers = {}
    for payout_method, defaults in provider_defaults.items():
        provider, _ = payout_provider_model.objects.get_or_create(
            code=defaults["code"],
            defaults={
                "name": defaults["name"],
                "payout_method": payout_method,
                "is_active": True,
            },
        )
        providers[payout_method] = provider

    active_fee_routes = (
        fee_rule_model.objects.filter(is_active=True)
        .values("corridor_id", "payout_method")
        .distinct()
    )

    for route in active_fee_routes:
        payout_method = route["payout_method"]
        provider = providers.get(payout_method)
        if provider is None:
            continue

        corridor_payout_method, _ = corridor_payout_method_model.objects.get_or_create(
            corridor_id=route["corridor_id"],
            payout_method=payout_method,
            defaults={
                "is_active": True,
                "display_order": provider_defaults[payout_method]["display_order"],
            },
        )
        corridor_payout_provider_model.objects.get_or_create(
            corridor_payout_method=corridor_payout_method,
            provider=provider,
            defaults={
                "is_active": True,
                "priority": 10,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('quotes', '0002_feerule_quotes_feer_corrido_3c367d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridorPayoutMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_method', models.CharField(choices=[('mobile_money', 'Mobile money'), ('bank_deposit', 'Bank deposit')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('min_send_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_send_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='countries.countrycorridor')),
            ],
            options={
                'ordering': ('display_order', 'payout_method'),
            },
        ),
        migrations.CreateModel(
            name='PayoutProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('payout_method', models.CharField(choices=[('mobile_money', 'Mobile money'), ('bank_deposit', 'Bank deposit')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('payout_method', 'name'),
                'indexes': [models.Index(fields=['payout_method', 'is_active'], name='countries_p_payout__357798_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorridorPayoutProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('min_send_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_send_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('corridor_payout_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='countries.corridorpayoutmethod')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridor_routes', to='countries.payoutprovider')),
            ],
            options={
                'ordering': ('priority', 'provider__name'),
            },
        ),
        migrations.AddIndex(
            model_name='corridorpayoutmethod',
            index=models.Index(fields=['corridor', 'payout_method', 'is_active'], name='countries_c_corrido_576230_idx'),
        ),
        migrations.AddConstraint(
            model_name='corridorpayoutmethod',
            constraint=models.UniqueConstraint(fields=('corridor', 'payout_method'), name='unique_corridor_payout_method'),
        ),
        migrations.AddConstraint(
            model_name='corridorpayoutmethod',
            constraint=models.CheckConstraint(condition=models.Q(('min_send_amount__isnull', True), ('min_send_amount__gte', 0), _connector='OR'), name='corridor_payout_method_min_send_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='corridorpayoutmethod',
            constraint=models.CheckConstraint(condition=models.Q(('max_send_amount__isnull', True), ('min_send_amount__isnull', True), ('max_send_amount__gte', models.F('min_send_amount')), _connector='OR'), name='corridor_payout_method_max_gte_min'),
        ),
        migrations.AddIndex(
            model_name='corridorpayoutprovider',
            index=models.Index(fields=['corridor_payout_method', 'is_active', 'priority'], name='countries_c_corrido_ba3051_idx'),
        ),
        migrations.AddConstraint(
            model_name='corridorpayoutprovider',
            constraint=models.UniqueConstraint(fields=('corridor_payout_method', 'provider'), name='unique_corridor_payout_provider'),
        ),
        migrations.AddConstraint(
            model_name='corridorpayoutprovider',
            constraint=models.CheckConstraint(condition=models.Q(('min_send_amount__isnull', True), ('min_send_amount__gte', 0), _connector='OR'), name='corridor_payout_provider_min_send_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='corridorpayoutprovider',
            constraint=models.CheckConstraint(condition=models.Q(('max_send_amount__isnull', True), ('min_send_amount__isnull', True), ('max_send_amount__gte', models.F('min_send_amount')), _connector='OR'), name='corridor_payout_provider_max_gte_min'),
        ),
        migrations.RunPython(
            seed_default_payout_routes,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
