# Generated by Django 5.2.13 on 2026-04-19 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('quotes', '0001_initial'),
        ('recipients', '0002_recipient_recipients__sender__77eb7b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feerule',
            index=models.Index(fields=['corridor', 'payout_method', 'is_active'], name='quotes_feer_corrido_3c367d_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['sender', 'status'], name='quotes_quot_sender__4523fc_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['source_country', 'destination_country', 'payout_method'], name='quotes_quot_source__9633f9_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['expires_at'], name='quotes_quot_expires_2e3f11_idx'),
        ),
        migrations.AddConstraint(
            model_name='feerule',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gte', 0)), name='fee_rule_min_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='feerule',
            constraint=models.CheckConstraint(condition=models.Q(('max_amount__gte', models.F('min_amount'))), name='fee_rule_max_amount_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='feerule',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_fee__gte', 0)), name='fee_rule_fixed_fee_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='feerule',
            constraint=models.CheckConstraint(condition=models.Q(('percentage_fee__gte', 0)), name='fee_rule_percentage_fee_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('send_amount__gt', 0)), name='quote_send_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0)), name='quote_fee_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='quote_exchange_rate_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('receive_amount__gt', 0)), name='quote_receive_amount_gt_0'),
        ),
    ]
