# Generated by Django 5.2.13 on 2026-04-20 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('quotes', '0002_feerule_quotes_feer_corrido_3c367d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('provider_name', models.CharField(default='manual', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='countries.countrycorridor')),
            ],
            options={
                'ordering': ('-effective_at', '-created_at'),
                'indexes': [models.Index(fields=['corridor', 'is_active', 'effective_at'], name='quotes_exch_corrido_2719f8_idx'), models.Index(fields=['expires_at'], name='quotes_exch_expires_7d663f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='exchange_rate_rate_gt_0'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('corridor', 'provider_name'), name='unique_active_exchange_rate_per_provider')],
            },
        ),
    ]
