from django.urls import path

from .views import (
    StaffComplianceExportView,
    StaffOperationalAuditExportView,
    StaffTransferAmlFlagReviewView,
    StaffTransferExportView,
    StaffTransferComplianceActionView,
    StaffTransferListView,
    StaffTransferPaymentActionView,
    StaffTransferPayoutAttemptView,
    StaffTransferPayoutProviderSyncView,
    StaffTransferPayoutRetryView,
    StaffTransferPayoutReverseView,
    StaffTransferPayoutStatusSyncView,
    StaffTransferReportView,
    StaffTransferSanctionsCheckReviewView,
    StaffTransferStatusTransitionView,
    TransferDetailView,
    TransferPaymentAuthorizationView,
    TransferStripeConfirmView,
    TransferFundingView,
    TransferListCreateView,
    TransferPaymentInstructionView,
    TransferPaymentWebhookView,
    TransferPayoutWebhookView,
)


urlpatterns = [
    path("", TransferListCreateView.as_view(), name="transfer-list-create"),
    path(
        "payment-webhooks/<str:provider_name>/",
        TransferPaymentWebhookView.as_view(),
        name="transfer-payment-webhook",
    ),
    path(
        "payout-webhooks/<str:provider_code>/",
        TransferPayoutWebhookView.as_view(),
        name="transfer-payout-webhook",
    ),
    path(
        "operations/",
        StaffTransferListView.as_view(),
        name="transfer-operations-list",
    ),
    path(
        "operations/reports/",
        StaffTransferReportView.as_view(),
        name="transfer-operations-reports",
    ),
    path(
        "operations/exports/transfers.csv",
        StaffTransferExportView.as_view(),
        name="transfer-operations-export-transfers",
    ),
    path(
        "operations/exports/compliance.csv",
        StaffComplianceExportView.as_view(),
        name="transfer-operations-export-compliance",
    ),
    path(
        "operations/exports/audit.csv",
        StaffOperationalAuditExportView.as_view(),
        name="transfer-operations-export-audit",
    ),
    path("<uuid:pk>/funding/", TransferFundingView.as_view(), name="transfer-funding"),
    path(
        "<uuid:pk>/payment-instructions/",
        TransferPaymentInstructionView.as_view(),
        name="transfer-payment-instructions",
    ),
    path(
        "<uuid:pk>/payment-instructions/<uuid:instruction_id>/authorize/",
        TransferPaymentAuthorizationView.as_view(),
        name="transfer-payment-instruction-authorize",
    ),
    path(
        "<uuid:pk>/payment-instructions/<uuid:instruction_id>/stripe-confirm/",
        TransferStripeConfirmView.as_view(),
        name="transfer-payment-instruction-stripe-confirm",
    ),
    path(
        "<uuid:pk>/status/",
        StaffTransferStatusTransitionView.as_view(),
        name="transfer-status-transition",
    ),
    path(
        "<uuid:pk>/payment-actions/",
        StaffTransferPaymentActionView.as_view(),
        name="transfer-payment-action",
    ),
    path(
        "<uuid:pk>/payout-attempts/",
        StaffTransferPayoutAttemptView.as_view(),
        name="transfer-payout-attempt-list",
    ),
    path(
        "<uuid:pk>/payout-attempts/<uuid:attempt_id>/sync/",
        StaffTransferPayoutStatusSyncView.as_view(),
        name="transfer-payout-attempt-sync",
    ),
    path(
        "<uuid:pk>/payout-attempts/<uuid:attempt_id>/provider-sync/",
        StaffTransferPayoutProviderSyncView.as_view(),
        name="transfer-payout-attempt-provider-sync",
    ),
    path(
        "<uuid:pk>/payout-attempts/<uuid:attempt_id>/retry/",
        StaffTransferPayoutRetryView.as_view(),
        name="transfer-payout-attempt-retry",
    ),
    path(
        "<uuid:pk>/payout-attempts/<uuid:attempt_id>/reverse/",
        StaffTransferPayoutReverseView.as_view(),
        name="transfer-payout-attempt-reverse",
    ),
    path(
        "<uuid:pk>/compliance-actions/",
        StaffTransferComplianceActionView.as_view(),
        name="transfer-compliance-action",
    ),
    path(
        "<uuid:pk>/sanctions-checks/<uuid:check_id>/review/",
        StaffTransferSanctionsCheckReviewView.as_view(),
        name="transfer-sanctions-check-review",
    ),
    path(
        "<uuid:pk>/aml-flags/<uuid:flag_id>/review/",
        StaffTransferAmlFlagReviewView.as_view(),
        name="transfer-aml-flag-review",
    ),
    path("<uuid:pk>/", TransferDetailView.as_view(), name="transfer-detail"),
]
