# Generated by Django 5.2.13 on 2026-04-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='senderprofile',
            index=models.Index(fields=['country', 'kyc_status'], name='accounts_se_country_9a5cfa_idx'),
        ),
    ]
