# Generated by Django 5.2.13 on 2026-04-20 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_senderprofile_accounts_se_country_9a5cfa_idx'),
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderprofile',
            name='kyc_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='senderprofile',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senderprofile',
            name='kyc_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sender_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='senderprofile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senderprofile',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('needs_review', 'Needs review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', max_length=24),
        ),
        migrations.AddIndex(
            model_name='senderprofile',
            index=models.Index(fields=['kyc_status', 'kyc_submitted_at'], name='accounts_se_kyc_sta_12d3cf_idx'),
        ),
    ]
