# Generated by Django 5.2.13 on 2026-04-22 01:13

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_senderprofile_kyc_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('government_id', 'Government ID'), ('proof_of_address', 'Proof of address'), ('selfie', 'Selfie'), ('source_of_funds', 'Source of funds'), ('other', 'Other')], max_length=40)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='uploaded', max_length=24)),
                ('encrypted_file', models.FileField(storage=apps.accounts.models.SecureDocumentStorage(), upload_to=apps.accounts.models.secure_document_upload_path)),
                ('encrypted_original_filename', models.TextField()),
                ('content_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveIntegerField()),
                ('sha256_digest', models.CharField(max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sender_documents', to=settings.AUTH_USER_MODEL)),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.senderprofile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_sender_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('review_sender_document', 'Can review sender verification documents'), ('download_sender_document', 'Can download sender verification documents')],
                'indexes': [models.Index(fields=['sender_profile', 'status'], name='accounts_se_sender__8f1179_idx'), models.Index(fields=['status', 'created_at'], name='accounts_se_status_34f9a6_idx'), models.Index(fields=['document_type', 'status'], name='accounts_se_documen_fe847e_idx'), models.Index(fields=['sha256_digest'], name='accounts_se_sha256__a663bf_idx')],
            },
        ),
    ]
