# Generated by Django 5.2.13 on 2026-04-22 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_senderdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderKycCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(max_length=120)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('clear', 'Clear'), ('needs_review', 'Needs review'), ('rejected', 'Rejected'), ('error', 'Error'), ('skipped', 'Skipped')], default='queued', max_length=24)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_checks', to='accounts.senderprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sender_profile', 'status'], name='accounts_se_sender__eca7bb_idx'), models.Index(fields=['provider_name', 'provider_reference'], name='accounts_se_provide_02c55f_idx'), models.Index(fields=['status', 'created_at'], name='accounts_se_status_710813_idx')],
            },
        ),
    ]
