# Generated by Django 5.2.13 on 2026-04-19 01:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('relationship_to_sender', models.CharField(blank=True, max_length=80)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='countries.country')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='RecipientBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=80)),
                ('account_name', models.CharField(blank=True, max_length=180)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('swift_code', models.CharField(blank=True, max_length=32)),
                ('is_default', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='recipients.recipient')),
            ],
            options={
                'ordering': ('bank_name', 'account_number'),
            },
        ),
        migrations.CreateModel(
            name='RecipientMobileMoneyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(max_length=32)),
                ('account_name', models.CharField(blank=True, max_length=180)),
                ('is_default', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_accounts', to='recipients.recipient')),
            ],
            options={
                'ordering': ('provider_name', 'mobile_number'),
            },
        ),
    ]
