# Generated by Django 5.2.13 on 2026-04-19 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('recipients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['sender', 'country'], name='recipients__sender__77eb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['sender', 'last_name', 'first_name'], name='recipients__sender__af0fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientbankaccount',
            index=models.Index(fields=['recipient', 'is_default'], name='recipients__recipie_fde53b_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientmobilemoneyaccount',
            index=models.Index(fields=['recipient', 'is_default'], name='recipients__recipie_f6bb0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipientbankaccount',
            constraint=models.UniqueConstraint(fields=('recipient', 'bank_name', 'account_number'), name='unique_recipient_bank_account'),
        ),
        migrations.AddConstraint(
            model_name='recipientmobilemoneyaccount',
            constraint=models.UniqueConstraint(fields=('recipient', 'provider_name', 'mobile_number'), name='unique_recipient_mobile_money_account'),
        ),
    ]
