# Generated by Django 5.2.13 on 2026-04-21 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('recipients', '0002_recipient_recipients__sender__77eb7b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='verification_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='verification_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipient',
            name='verification_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('needs_review', 'Needs review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', max_length=24),
        ),
        migrations.AddField(
            model_name='recipient',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['verification_status', 'verification_submitted_at'], name='recipients__verific_182181_idx'),
        ),
    ]
