# Generated by Django 5.2.13 on 2026-04-19 01:24

import apps.transfers.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('quotes', '0001_initial'),
        ('recipients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.transfers.models.generate_transfer_reference, editable=False, max_length=32, unique=True)),
                ('payout_method', models.CharField(choices=[('mobile_money', 'Mobile money'), ('bank_deposit', 'Bank deposit')], max_length=24)),
                ('send_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('receive_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('awaiting_funding', 'Awaiting funding'), ('funding_received', 'Funding received'), ('under_review', 'Under review'), ('approved', 'Approved'), ('processing_payout', 'Processing payout'), ('paid_out', 'Paid out'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='awaiting_funding', max_length=32)),
                ('funding_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('received', 'Received'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('compliance_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_more_info', 'Needs more information')], default='pending', max_length=32)),
                ('payout_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_started', max_length=32)),
                ('reason_for_transfer', models.CharField(blank=True, max_length=160)),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_transfers', to='countries.country')),
                ('destination_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_transfers', to='countries.currency')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='quotes.quote')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='recipients.recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to=settings.AUTH_USER_MODEL)),
                ('source_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_transfers', to='countries.country')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_transfers', to='countries.currency')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransferStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_status_events', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='transfers.transfer')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
