# Generated by Django 5.2.13 on 2026-04-19 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('quotes', '0002_feerule_quotes_feer_corrido_3c367d_idx_and_more'),
        ('recipients', '0002_recipient_recipients__sender__77eb7b_idx_and_more'),
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('quote_created', 'Quote created'), ('awaiting_funding', 'Awaiting funding'), ('funding_received', 'Funding received'), ('under_review', 'Under review'), ('approved', 'Approved'), ('processing_payout', 'Processing payout'), ('paid_out', 'Paid out'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='awaiting_funding', max_length=32),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['sender', 'status'], name='transfers_t_sender__523e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', 'created_at'], name='transfers_t_status_f3090c_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['funding_status'], name='transfers_t_funding_73ee20_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['compliance_status'], name='transfers_t_complia_44bad6_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['payout_status'], name='transfers_t_payout__e28a31_idx'),
        ),
        migrations.AddIndex(
            model_name='transferstatusevent',
            index=models.Index(fields=['transfer', 'created_at'], name='transfers_t_transfe_ed28ee_idx'),
        ),
        migrations.AddIndex(
            model_name='transferstatusevent',
            index=models.Index(fields=['to_status', 'created_at'], name='transfers_t_to_stat_6b7360_idx'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('send_amount__gt', 0)), name='transfer_send_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0)), name='transfer_fee_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='transfer_exchange_rate_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('receive_amount__gt', 0)), name='transfer_receive_amount_gt_0'),
        ),
    ]
