# Generated by Django 5.2.13 on 2026-04-20 19:14

import apps.transfers.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('transfers', '0002_alter_transfer_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPaymentInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('debit_card', 'Debit card'), ('bank_transfer', 'Bank transfer')], max_length=32)),
                ('provider_name', models.CharField(default='mock', max_length=120)),
                ('provider_reference', models.CharField(default=apps.transfers.models.generate_payment_reference, editable=False, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('instructions', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instructions', to='countries.currency')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_instructions', to='transfers.transfer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['transfer', 'status'], name='transfers_t_transfe_750b85_idx'), models.Index(fields=['provider_name', 'provider_reference'], name='transfers_t_provide_39b211_idx'), models.Index(fields=['expires_at'], name='transfers_t_expires_e676fe_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_instruction_amount_gt_0')],
            },
        ),
    ]
