# Generated by Django 5.2.13 on 2026-04-20 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_transferpaymentinstruction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='compliance_status',
            field=models.CharField(choices=[('clear', 'Clear'), ('flagged', 'Flagged'), ('on_hold', 'On hold'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_more_info', 'Needs more information'), ('not_required', 'Not required'), ('pending', 'Pending')], default='clear', max_length=32),
        ),
        migrations.CreateModel(
            name='TransferComplianceFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('kyc', 'KYC'), ('limit', 'Limit'), ('risk_rule', 'Risk rule'), ('sanctions', 'Sanctions'), ('aml', 'AML'), ('recipient', 'Recipient'), ('manual', 'Manual')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=24)),
                ('code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfer_compliance_flags', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_transfer_compliance_flags', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_flags', to='transfers.transfer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['transfer', 'status'], name='transfers_t_transfe_86992c_idx'), models.Index(fields=['category', 'severity'], name='transfers_t_categor_12c945_idx'), models.Index(fields=['code'], name='transfers_t_code_92ad0d_idx')],
            },
        ),
    ]
