# Generated by Django 5.2.13 on 2026-04-20 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('transfers', '0004_alter_transfer_compliance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLimitRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payout_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile money'), ('bank_deposit', 'Bank deposit')], max_length=24)),
                ('period', models.CharField(choices=[('per_transfer', 'Per transfer'), ('daily', 'Daily'), ('monthly', 'Monthly')], max_length=24)),
                ('max_send_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('action', models.CharField(choices=[('flag', 'Flag'), ('hold', 'Hold')], default='flag', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_limit_rules', to='countries.countrycorridor')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_limit_rules', to=settings.AUTH_USER_MODEL)),
                ('source_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_limit_rules', to='countries.currency')),
            ],
            options={
                'ordering': ('code',),
                'indexes': [models.Index(fields=['is_active', 'period'], name='transfers_t_is_acti_7afe92_idx'), models.Index(fields=['corridor', 'is_active'], name='transfers_t_corrido_fd2a83_idx'), models.Index(fields=['sender', 'is_active'], name='transfers_t_sender__77cb11_idx'), models.Index(fields=['source_currency', 'is_active'], name='transfers_t_source__5a1504_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_send_amount__gt', 0)), name='transfer_limit_rule_max_send_gt_0')],
            },
        ),
    ]
