# Generated by Django 5.2.13 on 2026-04-20 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('transfers', '0005_transferlimitrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRiskRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rule_type', models.CharField(choices=[('high_amount', 'High amount'), ('first_transfer', 'First transfer'), ('rapid_repeat', 'Rapid repeat transfer'), ('incomplete_profile', 'Incomplete sender profile'), ('unverified_kyc', 'Unverified KYC'), ('destination_method', 'Destination or method rule')], max_length=40)),
                ('payout_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile money'), ('bank_deposit', 'Bank deposit')], max_length=24)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Used by high amount rules.', max_digits=12, null=True)),
                ('repeat_count', models.PositiveIntegerField(blank=True, help_text='Used by rapid repeat rules.', null=True)),
                ('window_minutes', models.PositiveIntegerField(blank=True, help_text='Used by rapid repeat rules.', null=True)),
                ('action', models.CharField(choices=[('flag', 'Flag'), ('hold', 'Hold')], default='flag', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_risk_rules', to='countries.countrycorridor')),
                ('destination_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_risk_rules', to='countries.country')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_risk_rules', to=settings.AUTH_USER_MODEL)),
                ('source_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_risk_rules', to='countries.currency')),
            ],
            options={
                'ordering': ('code',),
                'indexes': [models.Index(fields=['is_active', 'rule_type'], name='transfers_t_is_acti_5f016b_idx'), models.Index(fields=['corridor', 'is_active'], name='transfers_t_corrido_466b49_idx'), models.Index(fields=['sender', 'is_active'], name='transfers_t_sender__6f6805_idx'), models.Index(fields=['source_currency', 'is_active'], name='transfers_t_source__339d9a_idx'), models.Index(fields=['destination_country', 'is_active'], name='transfers_t_destina_64dfed_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('threshold_amount__isnull', True), ('threshold_amount__gt', 0), _connector='OR'), name='risk_rule_threshold_gt_0_or_null'), models.CheckConstraint(condition=models.Q(('repeat_count__isnull', True), ('repeat_count__gt', 0), _connector='OR'), name='risk_rule_repeat_count_gt_0_or_null'), models.CheckConstraint(condition=models.Q(('window_minutes__isnull', True), ('window_minutes__gt', 0), _connector='OR'), name='risk_rule_window_gt_0_or_null')],
            },
        ),
    ]
