# Generated by Django 5.2.13 on 2026-04-20 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_transferriskrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferComplianceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('note', 'Note added'), ('hold', 'Hold applied'), ('review', 'Review started'), ('approve', 'Approved'), ('reject', 'Rejected')], max_length=24)),
                ('from_compliance_status', models.CharField(blank=True, max_length=32)),
                ('to_compliance_status', models.CharField(blank=True, max_length=32)),
                ('from_transfer_status', models.CharField(blank=True, max_length=32)),
                ('to_transfer_status', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_compliance_events', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_events', to='transfers.transfer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['transfer', 'created_at'], name='transfers_t_transfe_600a85_idx'), models.Index(fields=['action', 'created_at'], name='transfers_t_action_c8cda3_idx'), models.Index(fields=['to_compliance_status', 'created_at'], name='transfers_t_to_comp_c96524_idx')],
            },
        ),
    ]
