# Generated by Django 5.2.13 on 2026-04-21 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('transfers', '0007_transfercomplianceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientVerificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payout_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile money'), ('bank_deposit', 'Bank deposit')], max_length=24)),
                ('min_send_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('action', models.CharField(choices=[('flag', 'Flag'), ('hold', 'Hold')], default='hold', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_verification_rules', to='countries.countrycorridor')),
                ('destination_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_verification_rules', to='countries.country')),
                ('source_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_verification_rules', to='countries.currency')),
            ],
            options={
                'ordering': ('code',),
                'indexes': [models.Index(fields=['is_active', 'destination_country'], name='transfers_r_is_acti_2cd823_idx'), models.Index(fields=['corridor', 'is_active'], name='transfers_r_corrido_556705_idx'), models.Index(fields=['source_currency', 'is_active'], name='transfers_r_source__ef22e1_idx'), models.Index(fields=['payout_method', 'is_active'], name='transfers_r_payout__9e3fee_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_send_amount__isnull', True), ('min_send_amount__gt', 0), _connector='OR'), name='recipient_verification_rule_min_send_gt_0_or_null')],
            },
        ),
    ]
