# Generated by Django 5.2.13 on 2026-04-21 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0008_recipientverificationrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercomplianceevent',
            name='action',
            field=models.CharField(choices=[('note', 'Note added'), ('hold', 'Hold applied'), ('review', 'Review started'), ('approve', 'Approved'), ('reject', 'Rejected'), ('screening', 'Screening updated')], max_length=24),
        ),
        migrations.CreateModel(
            name='TransferSanctionsCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('sender', 'Sender'), ('recipient', 'Recipient')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('clear', 'Clear'), ('possible_match', 'Possible match'), ('confirmed_match', 'Confirmed match'), ('error', 'Error'), ('skipped', 'Skipped')], default='queued', max_length=24)),
                ('screened_name', models.CharField(max_length=180)),
                ('provider_name', models.CharField(default='pending_integration', max_length=120)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('screening_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfer_sanctions_checks', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_checks', to='transfers.transfer')),
            ],
            options={
                'ordering': ('party_type', 'created_at'),
                'indexes': [models.Index(fields=['transfer', 'status'], name='transfers_t_transfe_a0d474_idx'), models.Index(fields=['party_type', 'status'], name='transfers_t_party_t_6b8814_idx'), models.Index(fields=['reviewed_at'], name='transfers_t_reviewe_1b32f3_idx')],
                'constraints': [models.UniqueConstraint(fields=('transfer', 'party_type'), name='unique_transfer_sanctions_check_party')],
            },
        ),
    ]
