# Generated by Django 5.2.13 on 2026-04-21 00:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('transfers', '0009_alter_transfercomplianceevent_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercomplianceevent',
            name='action',
            field=models.CharField(choices=[('note', 'Note added'), ('hold', 'Hold applied'), ('review', 'Review started'), ('approve', 'Approved'), ('reject', 'Rejected'), ('screening', 'Screening updated'), ('aml', 'AML updated')], max_length=24),
        ),
        migrations.CreateModel(
            name='TransferAmlRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rule_type', models.CharField(choices=[('large_transfer', 'Large transfer amount'), ('daily_volume', 'Daily sender volume'), ('velocity_count', 'Velocity transfer count'), ('velocity_volume', 'Velocity transfer volume')], max_length=40)),
                ('payout_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile money'), ('bank_deposit', 'Bank deposit')], max_length=24)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Used by amount and volume monitoring rules.', max_digits=12, null=True)),
                ('transfer_count', models.PositiveIntegerField(blank=True, help_text='Used by velocity count monitoring rules.', null=True)),
                ('window_minutes', models.PositiveIntegerField(blank=True, help_text='Used by velocity monitoring rules.', null=True)),
                ('action', models.CharField(choices=[('flag', 'Flag'), ('hold', 'Hold')], default='flag', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_aml_rules', to='countries.countrycorridor')),
                ('destination_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_aml_rules', to='countries.country')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_aml_rules', to=settings.AUTH_USER_MODEL)),
                ('source_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_aml_rules', to='countries.currency')),
            ],
            options={
                'ordering': ('code',),
                'indexes': [models.Index(fields=['is_active', 'rule_type'], name='transfers_t_is_acti_fef0e8_idx'), models.Index(fields=['corridor', 'is_active'], name='transfers_t_corrido_d78022_idx'), models.Index(fields=['sender', 'is_active'], name='transfers_t_sender__8b62a0_idx'), models.Index(fields=['source_currency', 'is_active'], name='transfers_t_source__24f7ed_idx'), models.Index(fields=['destination_country', 'is_active'], name='transfers_t_destina_653d69_idx'), models.Index(fields=['payout_method', 'is_active'], name='transfers_t_payout__a1acf0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('threshold_amount__isnull', True), ('threshold_amount__gt', 0), _connector='OR'), name='aml_rule_threshold_gt_0_or_null'), models.CheckConstraint(condition=models.Q(('transfer_count__isnull', True), ('transfer_count__gt', 0), _connector='OR'), name='aml_rule_transfer_count_gt_0_or_null'), models.CheckConstraint(condition=models.Q(('window_minutes__isnull', True), ('window_minutes__gt', 0), _connector='OR'), name='aml_rule_window_gt_0_or_null')],
            },
        ),
    ]
