# Generated by Django 5.2.13 on 2026-04-21 00:50

from django.db import migrations, models


def migrate_payment_instruction_statuses(apps, schema_editor):
    TransferPaymentInstruction = apps.get_model(
        "transfers",
        "TransferPaymentInstruction",
    )
    status_map = {
        "pending": "not_started",
        "processing": "pending_authorization",
        "succeeded": "paid",
    }

    for old_status, new_status in status_map.items():
        TransferPaymentInstruction.objects.filter(status=old_status).update(
            status=new_status,
        )


def reverse_payment_instruction_statuses(apps, schema_editor):
    TransferPaymentInstruction = apps.get_model(
        "transfers",
        "TransferPaymentInstruction",
    )
    status_map = {
        "not_started": "pending",
        "pending_authorization": "processing",
        "paid": "succeeded",
    }

    for old_status, new_status in status_map.items():
        TransferPaymentInstruction.objects.filter(status=old_status).update(
            status=new_status,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0010_alter_transfercomplianceevent_action_transferamlrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferpaymentinstruction',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferpaymentinstruction',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferpaymentinstruction',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferpaymentinstruction',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferpaymentinstruction',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transferpaymentinstruction',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending_authorization', 'Pending authorization'), ('authorized', 'Authorized'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('requires_review', 'Requires review'), ('expired', 'Expired')], default='not_started', max_length=32),
        ),
        migrations.RunPython(
            migrate_payment_instruction_statuses,
            reverse_payment_instruction_statuses,
        ),
    ]
