# Generated by Django 5.2.13 on 2026-04-21 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0011_transferpaymentinstruction_authorized_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(max_length=120)),
                ('provider_event_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=120)),
                ('provider_reference', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=24)),
                ('processing_message', models.TextField(blank=True)),
                ('resulting_payment_status', models.CharField(blank=True, max_length=32)),
                ('event_created_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='transfers.transferpaymentinstruction')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider_name', 'provider_reference'], name='transfers_t_provide_f47b0a_idx'), models.Index(fields=['processing_status', 'created_at'], name='transfers_t_process_fd46d5_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_name', 'provider_event_id'), name='payment_webhook_provider_event_unique')],
            },
        ),
    ]
