# Generated by Django 5.2.13 on 2026-04-21 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('transfers', '0012_transferpaymentwebhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPaymentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('refund', 'Refund'), ('reversal', 'Reversal')], max_length=24)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed'), ('failed', 'Failed')], default='requested', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider_name', models.CharField(max_length=120)),
                ('provider_reference', models.CharField(max_length=64)),
                ('provider_action_reference', models.CharField(blank=True, max_length=120)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField()),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_actions', to='countries.currency')),
                ('payment_instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_actions', to='transfers.transferpaymentinstruction')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_actions_requested', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_actions', to='transfers.transfer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['transfer', 'action', 'status'], name='transfers_t_transfe_df5a59_idx'), models.Index(fields=['payment_instruction', 'action', 'status'], name='transfers_t_payment_fa4e96_idx'), models.Index(fields=['provider_name', 'provider_reference'], name='transfers_t_provide_b5f211_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_action_amount_gt_0')],
            },
        ),
    ]
