# Generated by Django 5.2.13 on 2026-04-21 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_countries_c_is_send_afb0d6_idx_and_more'),
        ('transfers', '0013_transferpaymentaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercomplianceflag',
            name='category',
            field=models.CharField(choices=[('kyc', 'KYC'), ('limit', 'Limit'), ('risk_rule', 'Risk rule'), ('payment', 'Payment'), ('sanctions', 'Sanctions'), ('aml', 'AML'), ('recipient', 'Recipient'), ('manual', 'Manual')], max_length=32),
        ),
        migrations.CreateModel(
            name='TransferPaymentFraudRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rule_type', models.CharField(choices=[('repeated_attempts', 'Repeated payment attempts'), ('cardholder_name_mismatch', 'Cardholder name mismatch'), ('unusual_amount', 'Unusual payment amount'), ('compliance_hold', 'Compliance hold')], max_length=40)),
                ('payout_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile money'), ('bank_deposit', 'Bank deposit')], max_length=24)),
                ('payment_method', models.CharField(blank=True, choices=[('debit_card', 'Debit card'), ('bank_transfer', 'Bank transfer')], max_length=32)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Used by unusual amount rules.', max_digits=12, null=True)),
                ('attempt_count', models.PositiveIntegerField(blank=True, help_text='Used by repeated attempt rules.', null=True)),
                ('window_minutes', models.PositiveIntegerField(blank=True, help_text='Used by repeated attempt rules.', null=True)),
                ('action', models.CharField(choices=[('flag', 'Flag'), ('hold', 'Hold')], default='flag', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('destination_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_fraud_rules', to='countries.country')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_fraud_rules', to=settings.AUTH_USER_MODEL)),
                ('source_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_fraud_rules', to='countries.currency')),
            ],
            options={
                'ordering': ('code',),
                'indexes': [models.Index(fields=['is_active', 'rule_type'], name='transfers_t_is_acti_156337_idx'), models.Index(fields=['sender', 'is_active'], name='transfers_t_sender__9a0f8e_idx'), models.Index(fields=['source_currency', 'is_active'], name='transfers_t_source__0445b6_idx'), models.Index(fields=['destination_country', 'is_active'], name='transfers_t_destina_1b01e8_idx'), models.Index(fields=['payment_method', 'is_active'], name='transfers_t_payment_7e1f2d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('threshold_amount__isnull', True), ('threshold_amount__gt', 0), _connector='OR'), name='payment_fraud_threshold_gt_0_or_null'), models.CheckConstraint(condition=models.Q(('attempt_count__isnull', True), ('attempt_count__gt', 0), _connector='OR'), name='payment_fraud_attempt_count_gt_0_or_null'), models.CheckConstraint(condition=models.Q(('window_minutes__isnull', True), ('window_minutes__gt', 0), _connector='OR'), name='payment_fraud_window_gt_0_or_null')],
            },
        ),
    ]
