# Generated by Django 5.2.13 on 2026-04-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_corridorpayoutmethod_payoutprovider_and_more'),
        ('transfers', '0014_alter_transfercomplianceflag_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='payout_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='countries.payoutprovider'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['payout_provider', 'payout_status'], name='transfers_t_payout__357f22_idx'),
        ),
    ]
