# Generated by Django 5.2.13 on 2026-04-21 17:36

import apps.transfers.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_corridorpayoutmethod_payoutprovider_and_more'),
        ('transfers', '0015_transfer_payout_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='payout_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('queued', 'Queued'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('paid', 'Paid'), ('paid_out', 'Paid out'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('retrying', 'Retrying')], default='not_started', max_length=32),
        ),
        migrations.CreateModel(
            name='TransferPayoutAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_method', models.CharField(choices=[('mobile_money', 'Mobile money'), ('bank_deposit', 'Bank deposit')], max_length=24)),
                ('provider_reference', models.CharField(default=apps.transfers.models.generate_payout_reference, editable=False, max_length=64, unique=True)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('paid_out', 'Paid out'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('retrying', 'Retrying')], default='queued', max_length=32)),
                ('provider_status', models.CharField(blank=True, max_length=80)),
                ('status_reason', models.TextField(blank=True)),
                ('destination_snapshot', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payout_attempts', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_attempts', to='countries.currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_attempts', to='countries.payoutprovider')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_attempts', to='transfers.transferpayoutattempt')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_attempts', to='transfers.transfer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransferPayoutEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submit', 'Submitted'), ('status_sync', 'Status sync'), ('fail', 'Failed'), ('retry', 'Retry'), ('reverse', 'Reversed')], max_length=24)),
                ('from_payout_status', models.CharField(blank=True, max_length=32)),
                ('to_payout_status', models.CharField(blank=True, max_length=32)),
                ('provider_event_id', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payout_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='transfers.transferpayoutattempt')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_payout_events', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_events', to='transfers.transfer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='transferpayoutattempt',
            index=models.Index(fields=['transfer', 'status'], name='transfers_t_transfe_af22dd_idx'),
        ),
        migrations.AddIndex(
            model_name='transferpayoutattempt',
            index=models.Index(fields=['provider', 'status'], name='transfers_t_provide_b66c47_idx'),
        ),
        migrations.AddIndex(
            model_name='transferpayoutattempt',
            index=models.Index(fields=['provider', 'provider_reference'], name='transfers_t_provide_8d174a_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferpayoutattempt',
            constraint=models.UniqueConstraint(fields=('transfer', 'attempt_number'), name='unique_transfer_payout_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='transferpayoutattempt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_attempt_amount_gt_0'),
        ),
        migrations.AddIndex(
            model_name='transferpayoutevent',
            index=models.Index(fields=['transfer', 'created_at'], name='transfers_t_transfe_5add04_idx'),
        ),
        migrations.AddIndex(
            model_name='transferpayoutevent',
            index=models.Index(fields=['payout_attempt', 'created_at'], name='transfers_t_payout__93f52c_idx'),
        ),
        migrations.AddIndex(
            model_name='transferpayoutevent',
            index=models.Index(fields=['action', 'created_at'], name='transfers_t_action_955ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='transferpayoutevent',
            index=models.Index(fields=['provider_event_id'], name='transfers_t_provide_067b68_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferpayoutevent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('payout_attempt', 'provider_event_id'), name='unique_payout_attempt_provider_event'),
        ),
    ]
