# Generated by Django 5.2.13 on 2026-04-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0016_alter_transfer_payout_status_transferpayoutattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferpaymentfraudrule',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit card'), ('debit_card', 'Debit card'), ('bank_transfer', 'Bank transfer')], max_length=32),
        ),
        migrations.AlterField(
            model_name='transferpaymentinstruction',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit card'), ('debit_card', 'Debit card'), ('bank_transfer', 'Bank transfer')], max_length=32),
        ),
    ]
