# Generated by Django 5.2.13 on 2026-04-21 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0017_alter_transferpaymentfraudrule_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=16)),
                ('event_type', models.CharField(choices=[('transfer_created', 'Transfer created'), ('payment_received', 'Payment received'), ('payout_complete', 'Payout complete'), ('transaction_failed', 'Transaction failed'), ('verification_required', 'Verification required'), ('receipt', 'Receipt')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('dedupe_key', models.CharField(max_length=220, unique=True)),
                ('trigger_model', models.CharField(blank=True, max_length=120)),
                ('trigger_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transfers.transfer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['transfer', 'event_type', 'channel'], name='transfers_t_transfe_01c88e_idx'), models.Index(fields=['status', 'created_at'], name='transfers_t_status_1494b0_idx'), models.Index(fields=['trigger_model', 'trigger_id'], name='transfers_t_trigger_517b67_idx')],
            },
        ),
    ]
