# Generated by Django 5.2.13 on 2026-04-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0019_transfer_fx_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfernotification',
            name='event_type',
            field=models.CharField(choices=[('transfer_created', 'Transfer created'), ('transfer_initiated', 'Transfer initiated'), ('transfer_in_progress', 'Transfer in progress'), ('transfer_completed', 'Transfer completed'), ('transfer_failed', 'Transfer failed'), ('payment_received', 'Payment received'), ('payout_complete', 'Payout complete'), ('transaction_failed', 'Transaction failed'), ('verification_required', 'Verification required'), ('receipt', 'Receipt')], max_length=40),
        ),
    ]
